// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdARsrIouvNdNNB2G9NV1p6w_I-dWcVjI',
    appId: '1:163196966457:web:3521ae7a20d4f645a4dfe8',
    messagingSenderId: '163196966457',
    projectId: 'citi-guide-31d31',
    authDomain: 'citi-guide-31d31.firebaseapp.com',
    databaseURL: 'https://citi-guide-31d31-default-rtdb.firebaseio.com/',
    storageBucket: 'citi-guide-31d31.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB31IKkLjNJ3DiDcYXrtaHdjmB2OztgYy8',
    appId: '1:163196966457:android:f1d1f9292b95c064a4dfe8',
    messagingSenderId: '163196966457',
    projectId: 'citi-guide-31d31',
    databaseURL: 'https://citi-guide-31d31-default-rtdb.firebaseio.com',
    storageBucket: 'citi-guide-31d31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGoC74dr6RChvsIRGj255jhbLLB1JEI1o',
    appId: '1:163196966457:ios:6d4e517216757701a4dfe8',
    messagingSenderId: '163196966457',
    projectId: 'citi-guide-31d31',
    databaseURL: 'https://citi-guide-31d31-default-rtdb.firebaseio.com',
    storageBucket: 'citi-guide-31d31.firebasestorage.app',
    iosBundleId: 'com.example.citiGuideApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGoC74dr6RChvsIRGj255jhbLLB1JEI1o',
    appId: '1:163196966457:ios:6d4e517216757701a4dfe8',
    messagingSenderId: '163196966457',
    projectId: 'citi-guide-31d31',
    databaseURL: 'https://citi-guide-31d31-default-rtdb.firebaseio.com',
    storageBucket: 'citi-guide-31d31.firebasestorage.app',
    iosBundleId: 'com.example.citiGuideApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdARsrIouvNdNNB2G9NV1p6w_I-dWcVjI',
    appId: '1:163196966457:web:cc160f1599af2dafa4dfe8',
    messagingSenderId: '163196966457',
    projectId: 'citi-guide-31d31',
    authDomain: 'citi-guide-31d31.firebaseapp.com',
    databaseURL: 'https://citi-guide-31d31-default-rtdb.firebaseio.com',
    storageBucket: 'citi-guide-31d31.firebasestorage.app',
  );
}
